# Generated by Django 3.2.9 on 2021-12-04 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                (
                    "post_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Text"), (1, "Youtube"), (2, "Image"), (3, "URL")]
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "text_body",
                    models.TextField(blank=True, max_length=10000, null=True),
                ),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, max_length=22, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socialonlyone_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
